name       : pymediainfo
version    : 2.2.1
release    : 4
source     :
    - https://github.com/sbraz/pymediainfo/archive/v2.2.1.tar.gz : 9d0d44c1b6f7001de4741bcf51425eca043c8b8d5944752521500f8c119fee32
license    : MIT
component  : programming.python
summary    : A Python wrapper around the MediaInfo command line utility
description: |
    This small package is a wrapper around the MediaInfo library. It works on Linux, Mac OS X and Windows.
builddeps  :
    - pkgconfig(libmediainfo)
    - pytest-runner
rundeps    :
    - libmediainfo
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        PYTEST_ADDOPTS='-k "not test_parse_url"' python3 setup.py test
    popd
