name       : pymediainfo
version    : 2.2.0
release    : 3
source     :
    - https://github.com/sbraz/pymediainfo/archive/v2.2.0.tar.gz : 2596cc1ebde1c992302d38636219c1776d6bd4a4c90fb9fa8a577520d34beeaa
license    : MIT
component  : programming.python
summary    : A Python wrapper around the MediaInfo command line utility
description: |
    This small package is a wrapper around the MediaInfo library. It works on Linux, Mac OS X and Windows.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - libmediainfo
    - python-setuptools
rundeps    :
    - libmediainfo
setup      : |
    %python3_setup
install    : |
    %python3_install
