name       : pymediainfo
version    : 2.3.0
release    : 5
source     :
    - git|https://github.com/sbraz/pymediainfo.git : v2.3.0
license    : MIT
component  : programming.python
summary    : A Python wrapper around the MediaInfo command line utility
description: |
    This small package is a wrapper around the MediaInfo library. It works on Linux, Mac OS X and Windows.
builddeps  :
    - pkgconfig(libmediainfo)
    - pytest-runner
    - python-setuptools-scm
rundeps    :
    - libmediainfo
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        PYTEST_ADDOPTS='-k "not test_parse_url"' python3 setup.py test
    popd
