name       : pymediainfo
version    : '3.0'
release    : 6
source     :
    - https://pypi.org/packages/source/p/pymediainfo/pymediainfo-3.0.tar.gz : e76cc5525c3fc5cba61073e12365dc06f303b261d8f923aaa6eac09bf8fab245
license    : MIT
component  : programming.python
summary    : A Python wrapper around the MediaInfo command line utility
description: |
    This small package is a wrapper around the MediaInfo library. It works on Linux, Mac OS X and Windows.
builddeps  :
    - pkgconfig(libmediainfo)
    - pkgconfig(python3)
    - python-setuptools-scm
    - pytest-runner
    - mediainfo
rundeps    :
    - libmediainfo
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export PYTEST_ADDOPTS='-k "not test_parse_url"'
    %python3_test
